name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/devops

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test

      - name: Build Docker Image
        run: docker build -t myapp .

      - name: Success Notification
        if: success()
        run: echo "Pipeline Success"

      - name: Failure Notification
        if: failure()
        run: echo "Pipeline Failed"